# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
  
stages:
- stage: Build
  jobs: 
  - job: FirstJob
    steps:
    - bash: echo FirstJob
  - job: secondJob
    steps:
    - bash: echo secondJob
- stage: DevDeploy
  dependsOn: Build
  jobs: 
  - job: DevDeploy
    steps:
     - bash: echo FirstJob
- stage: QA
  dependsOn: Build
  jobs: 
  - job: QA
    steps:
     - bash: echo FirstJob
- stage: UAT
  dependsOn: Build
  jobs: 
  - job: UAT
    steps:
     - bash: echo FirstJob

